--Dagens datum och klockslag
SELECT GETDATE()--Gammal
SELECT SYSDATETIME()--Ny

SELECT CAST(SYSDATETIME() AS DATE)--Datum
SELECT CAST(SYSDATETIME() AS TIME)--Klockslag
SELECT CAST(SYSDATETIME() AS TIME(2))--Klockslag två decimaler
SELECT CAST(SYSDATETIME() AS TIME(0))--Klockslag utan decimaler


SELECT YEAR(SYSDATETIME())--År
SELECT MONTH(SYSDATETIME())--Månad
SELECT DAY(SYSDATETIME())--Dag

SELECT DATEPART(YEAR,SYSDATETIME())
SELECT DATEPART(iso_week,SYSDATETIME())

SELECT DATEDIFF(MONTH,'1999-12-31',SYSDATETIME())--301

SELECT DATEADD(DAY,100,SYSDATETIME())--2025-05-02 

SELECT EOMONTH('2025-02-01')--2025-02-28
